# Generated by Django 5.0.6 on 2024-07-07 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('registration', '0002_user_email_user_firstname_user_lastname'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='profiles.profile'),
            preserve_default=False,
        ),
    ]
